import browser_cookie3
import os

def export_facebook_cookies():
    cookie_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cookies.txt")
    print("Extracting Facebook cookies from Chrome...")
    try:
        cj = browser_cookie3.chrome(domain_name="facebook.com")
        cookies = list(cj)
        
        has_cuser = any(c.name == 'c_user' for c in cookies)
        if not has_cuser:
            print("ERROR: c_user cookie not found in Chrome. Are you logged into Facebook on your main Chrome browser?")
            return False
            
        print(f"Success! Found {len(cookies)} Facebook cookies including c_user.")
        
        # Merge with existing cookies if present
        existing_other_cookies = []
        if os.path.exists(cookie_path):
            with open(cookie_path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    if line.strip() and not line.startswith("#"):
                        parts = line.strip().split("\t")
                        if len(parts) >= 7 and "facebook.com" not in parts[0]:
                            existing_other_cookies.append(line.strip())

        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by Auto Cookie Extractor",
            ""
        ]
        lines.extend(existing_other_cookies)
        
        for c in cookies:
            domain = c.domain if c.domain.startswith(".") else "." + c.domain.lstrip(".")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.path
            secure = "TRUE" if c.secure else "FALSE"
            expires = str(int(c.expires)) if c.expires else "0"
            name = c.name
            value = c.value
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
            
        with open(cookie_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
            
        print("Successfully saved to cookies.txt!")
        return True
    except Exception as e:
        print(f"Failed to extract cookies: {e}")
        return False

if __name__ == "__main__":
    export_facebook_cookies()
