import asyncio
import os
import sys
from playwright.async_api import async_playwright

async def login_and_save_cookies():
    print("==================================================", flush=True)
    print("      Facebook Auto-Login & Cookie Generator", flush=True)
    print("==================================================", flush=True)
    print("Opening browser window... Please log in to your Facebook account.", flush=True)
    
    project_root = os.path.dirname(os.path.abspath(__file__))
    cookie_path = os.path.join(project_root, "cookies.txt")
    
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
            viewport={'width': 1280, 'height': 900},
            locale="th-TH"
        )
        page = await context.new_page()
        await page.goto("https://www.facebook.com/login", wait_until="domcontentloaded")
        
        print("\nWaiting for you to log in on the opened browser window...", flush=True)
        print("(Once you successfully log in, this script will automatically save cookies.txt and close!)\n", flush=True)
        
        for i in range(150):  # 5 minutes wait
            await asyncio.sleep(2)
            try:
                cookies = await context.cookies()
            except Exception:
                break
                
            has_cuser = any(c['name'] == 'c_user' for c in cookies)
            has_xs = any(c['name'] == 'xs' for c in cookies)
            
            if has_cuser or has_xs:
                print(f"Login detected! (c_user found). Saving {len(cookies)} cookies to cookies.txt...", flush=True)
                
                # Merge existing non-facebook cookies if they exist
                existing_other_cookies = []
                if os.path.exists(cookie_path):
                    with open(cookie_path, "r", encoding="utf-8", errors="ignore") as f:
                        for line in f:
                            if line.strip() and not line.startswith("#"):
                                parts = line.strip().split("\t")
                                if len(parts) >= 7 and "facebook.com" not in parts[0]:
                                    existing_other_cookies.append(line.strip())
                                    
                lines = [
                    "# Netscape HTTP Cookie File",
                    "# Generated by Facebook Auto-Login Tool",
                    ""
                ]
                
                # Add existing cookies for other sites
                lines.extend(existing_other_cookies)
                
                # Add Facebook cookies
                for c in cookies:
                    domain = c['domain']
                    flag = "TRUE" if domain.startswith(".") else "FALSE"
                    path = c.get('path', '/')
                    secure = "TRUE" if c.get('secure') else "FALSE"
                    expires = str(int(c.get('expires', 0))) if c.get('expires', 0) > 0 else "0"
                    name = c['name']
                    value = c['value']
                    lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
                    
                with open(cookie_path, "w", encoding="utf-8") as f:
                    f.write("\n".join(lines) + "\n")
                    
                print("==================================================", flush=True)
                print(" SUCCESS! cookies.txt has been updated with your Facebook login session.", flush=True)
                print(" Facebook will now allow scraping thousands of videos without guest limit!", flush=True)
                print("==================================================", flush=True)
                
                await asyncio.sleep(2)
                await browser.close()
                return True
                
        print("Login timed out or window was closed.", flush=True)
        try:
            await browser.close()
        except Exception:
            pass
        return False

if __name__ == "__main__":
    asyncio.run(login_and_save_cookies())
